"""修改了数据库

Revision ID: 401195e2c7e7
Revises: b2c1b51a6fd8
Create Date: 2019-05-29 21:39:09.705985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401195e2c7e7'
down_revision = 'b2c1b51a6fd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'news', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.drop_column('news', 'user_id')
    # ### end Alembic commands ###
